version: '3.8'

services:

  consul-server-1:
    image: consul
    ports: 
      - '8500:8500'
    command: agent -bind 0.0.0.0 -client 0.0.0.0 -dns-port 53 -bootstrap-expect 2 -config-file=/consul/config/consul-server-1-config.json
    volumes:
      - ./consul-server-1/config:/consul/config
      - ./consul-server-1/data:/consul/data
      - ./consul-certificate:/consul-certificate
      - ./consul-snapshort:/consul-snapshort

  consul-server-2:
    image: consul
    command: agent -bind 0.0.0.0 -client 0.0.0.0 -dns-port 53 -bootstrap-expect 2 -config-file=/consul/config/consul-server-2-config.json
    volumes:
      - ./consul-server-2/config:/consul/config
      - ./consul-server-2/data:/consul/data
      - ./consul-certificate:/consul-certificate
      - ./consul-snapshort:/consul-snapshort

  consul-client-1:
    image: consul
    command: agent -bind 0.0.0.0 -client 0.0.0.0 -dns-port 53 -config-file=/consul/config/consul-client-1-config.json
    volumes:
      - ./consul-client-1/config:/consul/config
      - ./consul-client-1/data:/consul/data
      - ./consul-certificate:/consul-certificate
      - ./consul-snapshort:/consul-snapshort
    depends_on:
      - consul-server-1

  vault-server-1:
    image: vault
    ports:
      - 8200:8200
    volumes:
      - ./vault-server-1/config:/vault/config
      - ./vault-server-1/policies:/vault/policies
      - ./vault-server-1/data:/vault/data
      - ./vault-server-1/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
    command: vault server -config=/vault/config/vault-server-1-config.json
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul-client-1
